- name: Install tomcat
  hosts: webserver
  gather_facts: false
  become: true
  tasks:
    - name: update apt
      apt:
        name: "*"
        state: latest
    - name: dir create
      file:
        path: /opt/tomcat
        state: directory
        mode: 0755
    - name: java install
      apt:
        name: openjdk-11-jdk
        state: present
    - name: get URL
      get_url:
        url: https://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.65/bin/apache-tomcat-8.5.65.tar.gz
        dest: /opt
    - name: untar
      unarchive:
        src: /opt/apache-tomcat-8.5.65.tar.gz
        dest: /opt
        remote_src: yes
    - name: move
      command: mv /opt/apache-tomcat-8.5.65 /opt/tomcat
    - name: Start tomcat
      shell: nohup /opt/tomcat/apache-tomcat-8.5.65/bin/startup.sh
